server {
    listen 127.0.0.1:8080;
    client_max_body_size 10000;

    error_page 404 /home/mvan-rij/Rank5/webserv/assets/errors/404.html;

    location / {
        methods GET HEAD;
        root /home/mvan-rij/Rank5/webserv/srcs;

        autoindex on;
    }

    location /srcs {
        methods GET HEAD;
        root /home/mvan-rij/Rank5/webserv/srcs;
        autoindex on;
    }
}
