name: webserv_CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang 18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-18 libc++-18-dev libc++abi-18-dev
      # - name: Build
      #   run: make

      - name: Run unit tests
        run: make CPPFLAGS="-MMD --std=c++23 -stdlib=libc++" LDFLAGS="-stdlib=libc++" CPP=clang++-18 test

      - name: Run end to end tests
        run: |
          go version
          nc --version
          make CPPFLAGS="-MMD --std=c++23 -stdlib=libc++" LDFLAGS="-stdlib=libc++" CPP=clang++-18 test_end_to_end

