name: webserv_CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build
      #   run: make

      - name: Clang format dry run
        run: git ls-files '*.cpp' '*.hpp' | xargs -r clang-format --dry-run --Werror

      - name: Run tests
        run: make CPPFLAGS="-MMD --std=c++23" LDFLAGS="" test
      
